A1:
  pokemon: "Bulbizarre"    
A2:
  pokemon: "Reptincel"     
A3:
  pokemon: "Pikachu"       
B1:
  pokemon: "Héricendre"    
B2:
  pokemon: "Feurisson"     
B3:
  pokemon: "Mentali"       
C1:
  pokemon: "Arcko"         
C2:
  pokemon: "Gobou"         
C3:
  pokemon: "Éoko"          
D1:
  pokemon: "Tiplouf"       
D2:
  pokemon: "Tortipouss"    
D3:
  pokemon: "Riolu"       
E1:
  pokemon: "Vipélierre"    
E2:
  pokemon: "Gruikui"       
E3:
  pokemon: "Braisillon"    
F1:
  pokemon: "Gruikui"       
F2:
  pokemon: "Grenousse"     
F3:
  pokemon: "Pandespiègle"  
G1:
  pokemon: "Germignon"     
G2:
  pokemon: "Kaïminus"      
G3:
  pokemon: "Manglouton"    
H1:
  pokemon: "Brindibou"     
H2:
  pokemon: "Flambino"      
H3:
  pokemon: "Tournicoton"   
I1:
  pokemon: "Otarlette"     
I2:
  pokemon: "Ouistempo"     
I3:
  pokemon: "Flambino"      