A9:
  pokemon: "Carapuce"       
B9:
  pokemon: "Kaïminus"       
C9:
  pokemon: "Gobou"          
D9:
  pokemon: "Mélokrik"       
E9:
  pokemon: "Ronflex"     
F9:
  pokemon: "Ronflex"       
G9:
  pokemon: "Flambino"       
H9:
  pokemon: "Flabébé"          
I9:
  pokemon: "Ouistempo"      

A8:
  pokemon: "Herbizarre"     
B8:
  pokemon: "Feurisson"      
C8:
  pokemon: "Tygnon"       
D8:
  pokemon: "Griknot"        
E8:
  pokemon: "Roussil"      
F8:
  pokemon: "Croâporal"     
G8:
  pokemon: "Rocabot"        
H8:
  pokemon: "Brocelôme"          
I8:
  pokemon: "Théffroi"       

A7:
  pokemon: "Salamèche"     
B7:
  pokemon: "Marill"      
C7:
  pokemon: "Poussifeu"      
D7:
  pokemon: "Tortipouss"     
E7:
  pokemon: "Chinchidou"     
F7:
  pokemon: "Feunnec"        
G7:
  pokemon: "Flambino"       
H7:
  pokemon: "Psystigri"          
I7:
  pokemon: "Stalgamin"       