A1:
    pokemon: "Gigalithe"
    player: 1
B1:
    pokemon: "Bétochef"
    player: 1
C1:
    pokemon: "Crocorible"
    player: 1
D1:
    pokemon: "Reshiram"
    player: 1
E1:
    pokemon: "Kyurem"
    player: 1
F1:
    pokemon: "Zekrom"
    player: 1
G1:
    pokemon: "Ohmassacre"
    player: 1
H1:
    pokemon: "Tranchodon"
    player: 1
I1:
    pokemon: "Polagriffe"
    player: 1

A2:
    pokemon: "Lugulabre"
    player: 1
B2:
    pokemon: "Trioxhydre"
    player: 1
C2:
    pokemon: "Sidérella"
    player: 1
D2:
    pokemon: "Clamiral"
    player: 1
E2:
    pokemon: "Roitiflam"
    player: 1
F2:
    pokemon: "Majaspic"
    player: 1
G2:
    pokemon: "Déflaisan"
    player: 1
H2:
    pokemon: "Cliticlic"
    player: 1
I2:
    pokemon: "Shaofouine"
    player: 1

C3:
    pokemon: "Golemastoc"
    player: 1
D3:
    pokemon: "Guériaigle"
    player: 1
E3:
    pokemon: "Pyrax"
    player: 1
F3:
    pokemon: "Sorbouboul"
    player: 1
G3:
    pokemon: "Zoroark"
    player: 1

A9:
    pokemon: "Gigalithe"
    player: 2
B9:
    pokemon: "Bétochef"
    player: 2
C9:
    pokemon: "Crocorible"
    player: 2
D9:
    pokemon: "Reshiram"
    player: 2
E9:
    pokemon: "Kyurem"
    player: 2
F9:
    pokemon: "Zekrom"
    player: 2
G9:
    pokemon: "Ohmassacre"
    player: 2
H9:
    pokemon: "Tranchodon"
    player: 2
I9:
    pokemon: "Polagriffe"
    player: 2

A8:
    pokemon: "Lugulabre"
    player: 2
B8:
    pokemon: "Trioxhydre"
    player: 2
C8:
    pokemon: "Sidérella"
    player: 2
D8:
    pokemon: "Clamiral"
    player: 2
E8:
    pokemon: "Roitiflam"
    player: 2
F8:
    pokemon: "Majaspic"
    player: 2
G8:
    pokemon: "Deflaisan"
    player: 2
H8:
    pokemon: "Cliticlic"
    player: 2
I8:
    pokemon: "Shaofouine"
    player: 2

C7:
    pokemon: "Golemastoc"
    player: 2
D7:
    pokemon: "Guériaigle"
    player: 2
E7:
    pokemon: "Pyrax"
    player: 2
F7:
    pokemon: "Sorbouboul"
    player: 2
G7:
    pokemon: "Zoroark"
    player: 2