A1:
    pokemon: "Baojian"
    player: 1
B1:
    pokemon: "Garde-de-Fer"
    player: 1
C1:
    pokemon: "Ogerpon"
    player: 1
D1:
    pokemon: "Koraidon"
    player: 1
E1:
    pokemon: "Térapagos"
    player: 1
F1:
    pokemon: "Miraidon"
    player: 1
G1:
    pokemon: "Pêchaminus"
    player: 1
H1:
    pokemon: "Rugit-Lune"
    player: 1
I1:
    pokemon: "Yuyu"
    player: 1

A2:
    pokemon: "Pomdorochi"
    player: 1
B2:
    pokemon: "Courrousinge"
    player: 1
C2:
    pokemon: "Carmadura"
    player: 1
D2:
    pokemon: "Palmaval"
    player: 1
E2:
    pokemon: "Flâmigator"
    player: 1
F2:
    pokemon: "Miascarade"
    player: 1
G2:
    pokemon: "Malvalame"
    player: 1
H2:
    pokemon: "Glaivodo"
    player: 1
I2:
    pokemon: "Gromago"
    player: 1

C3:
    pokemon: "Arboliva"
    player: 1
D3:
    pokemon: "Ampibidou"
    player: 1
E3:
    pokemon: "Forgelina"
    player: 1
F3:
    pokemon: "Tomberro"
    player: 1
G3:
    pokemon: "Terraiste"
    player: 1


A9:
    pokemon: "Baojian"
    player: 2
B9:
    pokemon: "Garde-de-Fer"
    player: 2
C9:
    pokemon: "Ogerpon"
    player: 2
D9:
    pokemon: "Koraidon"
    player: 2
E9:
    pokemon: "Térapagos"
    player: 2
F9:
    pokemon: "Miraidon"
    player: 2
G9:
    pokemon: "Pêchaminus"
    player: 2
H9:
    pokemon: "Rugit-Lune"
    player: 2
I9:
    pokemon: "Yuyu"
    player: 2

A8:
    pokemon: "Pomdorochi"
    player: 2
B8:
    pokemon: "Courrousinge"
    player: 2
C8:
    pokemon: "Carmadura"
    player: 2
D8:
    pokemon: "Palmaval"
    player: 2
E8:
    pokemon: "Flâmigator"
    player: 2
F8:
    pokemon: "Miascarade"
    player: 2
G8:
    pokemon: "Malvalame"
    player: 2
H8:
    pokemon: "Glaivodo"
    player: 2
I8:
    pokemon: "Gromago"
    player: 2

C7:
    pokemon: "Arboliva"
    player: 2
D7:
    pokemon: "Ampibidou"
    player: 2
E7:
    pokemon: "Forgelina"
    player: 2
F7:
    pokemon: "Tomberro"
    player: 2
G7:
    pokemon: "Terraiste"
    player: 2