name: AI Documentation Proposal

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  propose-docs:
    runs-on: self-hosted

    steps:
      -
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect modified files
        id: files
        run: |
          FILES=$(git diff --name-only \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.event.pull_request.head.sha }} || true)
          echo "files=$FILES" >> $GITHUB_OUTPUT

      - name: Build AI context
        run: |
          echo "### DIFF CODE" > context.txt
          git diff \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.event.pull_request.head.sha }} >> context.txt

          if [ -f README.md ]; then
            echo "\n### README" >> context.txt
            cat README.md >> context.txt
          fi

          if [ -d docs ]; then
            for file in docs/*.md; do
              [ -f "$file" ] || continue
              echo "\n### FILE: $file" >> context.txt
              cat "$file" >> context.txt
              echo "\n### END FILE" >> context.txt
            done
          fi

      - name: Generate documentation patch with Ollama
        id: generate_docs
        run: |
          CONTEXT=$(sed 's/"/\\"/g' context.txt | tr -d '\n')

          curl -s http://${{APP_ID}}/api/generate \
            -H "Content-Type: application/json" \
            -d "{
              \"model\": \"${{AI_MODEL}}\",
              \"prompt\": \"Tu es un assistant de documentation logicielle.
          Tu répondras avec la nouvelle documentation sous le même format que la documentation fournit en contexte 
          Objectif : mettre à jour ou créer :
           - docs/installation.md
           - docs/utilisateur.md
           - docs/technique.md
           - README.md
           - CHANGELOG.md
          Contraintes :
          - Aucun texte hors patch.
          - Format diff --git uniquement.
          - Markdown valide.
          - Si fichier absent → créer.
          - Basé STRICTEMENT sur le contexte suivant :
            $CONTEXT\"
          }" > patch.txt

      - name: Validate patch
        run: |
          git apply --check patch.txt || exit 1

# 6 — Upload artefact pour revue humaine
      - name: Upload patch artifact
        uses: actions/upload-artifact@v3
        with:
          name: ai-doc-patch
          path: patch.txt

# 7 — Commentaire automatique sur la PR
      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "Patch de documentation généré par IA disponible en artefact. Vérification humaine requise avant application."
            })
